### ISSUE TITLE
Error: useLocation() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by vectorCodes** [botmate/botmate#59]
**Describe the bug**

**To Reproduce**
1. Create new botmate project
2. Install any plugin
3. Load the dashboard
4. Go to settings page

**Expected behavior**
It should show up the settings page

**Screenshots**

<img width="711" alt="Screenshot 2024-09-19 at 4 56 11 PM" src="https://github.com/user-attachments/assets/5696378b-878f-4d35-af8d-de8305db27b3">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser : arc

**Comment by aleroldan156** [comment]
maybe this will help
https://bit.ly/4gwC82r

you may need to install the c compiler

**Comment by vectorCodes** [comment]
thnx it's working now
